server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/REALM_SPRING_API
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: CLIENT_SPRING
            client-secret: diD9HM8yU71SoZLU8agt4cuv0oUuELmu
            authorization-grant-type: authorization_code
            scope: openid
            auth-uri: http://localhost:8080/realms/REALM_SPRING_API
            realm: REALM_SPRING_API

logging:
  level:
    org:
      springframework:
        security: DEBUG
